services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm start:dev
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./nest-cli.json:/app/nest-cli.json
    environment:
      NODE_ENV: development
